version: '3.8'

services:
  frontend:
    image: webrtc
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_WSO2_IS_URL=https://localhost:9443
      - REACT_APP_WSO2_CLIENT_ID=${WSO2_CLIENT_ID}
      - REACT_APP_WSO2_CLIENT_SECRET=${WSO2_CLIENT_SECRET}
      - REACT_APP_WSO2_REDIRECT_URI=http://localhost:3000/api/auth/callback
    command: npm start
